- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v2.4.0
  hooks:
    - id: check-merge-conflict
    - id: debug-statements
    - id: name-tests-test
      args: ["--django"]
- repo: https://github.com/psf/black
  rev: "959848c17639bfc646128f6b582c5858164a5001"
  hooks:
    - id: black
      language_version: python3.7
- repo: https://gitlab.com/pycqa/flake8
  rev: 3.7.8
  hooks:
    - id: flake8
      args: [--max-line-length=120]
- repo: https://github.com/PyCQA/bandit
  rev: 1.6.2
  hooks:
    - id: bandit
      args: [-l, --recursive, -x, tests]
      files: .py$
